export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	 {
      "type": "input",
      "label": "计划分类",
      "prop": "categoryId",
      "span": 12
    },	  {
      "type": "input",
      "label": "计划名称",
      "prop": "planName",
      "span": 12
    },	  {
      "type": "input",
      "label": "开始时间",
      "prop": "startTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "规划结束时间",
      "prop": "plannedEndTime",
      "span": 12
    },	  {
      "type": "input",
      "label": "是否延期",
      "prop": "delayOrNot",
      "span": 12
    },	  {
      "type": "input",
      "label": "上传笔记",
      "prop": "whetherToUploadNotes",
      "span": 12
    },	  {
      "type": "input",
      "label": "笔记路径",
      "prop": "notePath",
      "span": 12
    },	 {
      "type": "input",
      "label": "学习路径",
      "prop": "learningPath",
      "span": 12
    },	 {
      "type": "input",
      "label": "当前进度",
      "prop": "currentProgress",
      "span": 12
    },	  {
      "type": "input",
      "label": "备注",
      "prop": "note",
      "span": 12
    },	  {
      "type": "input",
      "label": "当前状态",
      "prop": "status",
      "span": 12
    }  ]
}
